public class FlagshipIntegrationHelper {

    public static String CAMPAIGNS_URL = "https://decision.flagship.io/v2/%s/campaigns/?exposeAllKeys=true";
    public static String BUCKETING_URL = "https://cdn.flagship.io/%s/bucketing.json";
    public static String ACTIVATION_URL = "https://decision.flagship.io/v2/activate";
    public static String CONTEXT_URL = "https://decision.flagship.io/v2/%s/events";
    public static String CONSENT_PARAM = "&sendContextEvent=false";
    public static String ARIANE_URL = "https://ariane.abtasty.com";
    public static String _ENV_ID_ = "_ENV_ID_";
    public static String _API_KEY_ = "_API_KEY_";


    public static final String synchronizeResponse = "{\"visitorId\":\"visitor_1\",\"campaigns\":[{\"id\":\"xxxxxxjh6h101fk8lbrg\",\"variationGroupId\":\"xxxxxxjh6h101fk8lbsg\",\"variation\":{\"id\":\"xxxxxx65k9h02cuc1ae0\",\"modifications\":{\"type\":\"JSON\",\"value\":{\"isref\":\"not a all\"}},\"reference\":false}},{\"id\":\"xxxxxx3m649g0h9nkui0\",\"variationGroupId\":\"xxxxxx3m649g0h9nkuj0\",\"variation\":{\"id\":\"xxxxxx3m649g0h9nkuk0\",\"modifications\":{\"type\":\"FLAG\",\"value\":{\"release\":100}},\"reference\":false}}]}";
    public static final String synchronizeResponse2 = "{\"visitorId\":\"visitor_1\",\"campaigns\":[{\"id\":\"xxxxxx4jaeg0gm49cjg\",\"variationGroupId\":\"xxxxxx4jaeg0gm49ckg\",\"variation\":{\"id\":\"xxxxxx4jaeg0gm49cn0\",\"modifications\":{\"type\":\"JSON\",\"value\":{\"title\":\"Hello\",\"visitorIdColor\":\"#E5B21D\"}},\"reference\":false}},{\"id\":\"xxxxxxe4jaeg0gi1bhog\",\"variationGroupId\":\"xxxxxxe4jaeg0gi1bhpg\",\"variation\":{\"id\":\"xxxxxxe4jaeg0gi1bhq0\",\"modifications\":{\"type\":\"FLAG\",\"value\":{\"featureEnabled\":true}},\"reference\":false}},{\"id\":\"xxxxxxjh6h101fk8lbrg\",\"variationGroupId\":\"xxxxxxjh6h101fk8lbsg\",\"variation\":{\"id\":\"xxxxxx65k9h02cuc1ae0\",\"modifications\":{\"type\":\"JSON\",\"value\":{\"isref\":\"not a all\"}},\"reference\":false}},{\"id\":\"xxxxxx3m649g0h9nkui0\",\"variationGroupId\":\"xxxxxx3m649g0h9nkuj0\",\"variation\":{\"id\":\"xxxxxx3m649g0h9nkuk0\",\"modifications\":{\"type\":\"FLAG\",\"value\":{\"release\":100}},\"reference\":false}},{\"id\":\"xxxxxxc8tbo3s7bp5il0\",\"variationGroupId\":\"xxxxxxc8tbo3s7bp5im0\",\"variation\":{\"id\":\"xxxxxxc8tbo3s7bp5in0\",\"modifications\":{\"type\":\"JSON\",\"value\":{\"all_users\":1}},\"reference\":false}}]}";
    public static final String panic = "{\"panic\":true}";
    public static final String bucketingResponse = "{\"campaigns\":[{\"variationGroups\":[{\"targeting\":{\"targetingGroups\":[{\"targetings\":[{\"value\":true,\"operator\":\"EQUALS\",\"key\":\"isVIPUser\"}]}]},\"variations\":[{\"allocation\":100,\"id\":\"xxxxxxe4jaeg0gi1bhq0\",\"modifications\":{\"type\":\"FLAG\",\"value\":{\"featureEnabled\":true}}}],\"id\":\"xxxxxxe4jaeg0gi1bhpg\"},{\"targeting\":{\"targetingGroups\":[{\"targetings\":[{\"value\":false,\"operator\":\"EQUALS\",\"key\":\"isVIPUser\"}]}]},\"variations\":[{\"allocation\":100,\"id\":\"xxxxxxe4jaeg0gi1bhr0\",\"modifications\":{\"type\":\"FLAG\",\"value\":{\"featureEnabled\":false}}}],\"id\":\"xxxxxxe4jaeg0gi1bhqg\"}],\"id\":\"xxxxxxe4jaeg0gi1bhog\",\"type\":\"toggle\",\"customId\":\"enableFeatureVIP\"},{\"variationGroups\":[{\"targeting\":{\"targetingGroups\":[{\"targetings\":[{\"value\":\"\",\"operator\":\"EQUALS\",\"key\":\"fs_all_users\"}]}]},\"variations\":[{\"reference\":true,\"id\":\"xxxxxx3m649g0h9nkujg\",\"modifications\":{\"type\":\"FLAG\",\"value\":{\"release\":null}}},{\"allocation\":100,\"id\":\"xxxxxx3m649g0h9nkuk0\",\"modifications\":{\"type\":\"FLAG\",\"value\":{\"release\":100}}}],\"id\":\"xxxxxx3m649g0h9nkuj0\"}],\"id\":\"xxxxxx3m649g0h9nkui0\",\"type\":\"deployment\"},{\"variationGroups\":[{\"targeting\":{\"targetingGroups\":[{\"targetings\":[{\"value\":true,\"operator\":\"EQUALS\",\"key\":\"ab10_enabled\"}]}]},\"variations\":[{\"reference\":true,\"allocation\":10,\"id\":\"xxxxxxc3fk9jdb020um0\",\"modifications\":{\"type\":\"JSON\",\"value\":{\"ab10_variation\":null}}},{\"allocation\":10,\"id\":\"xxxxxxc3fk9jdb020umg\",\"modifications\":{\"type\":\"JSON\",\"value\":{\"ab10_variation\":1}}},{\"allocation\":10,\"id\":\"xxxxxx8bcahim71g8290\",\"modifications\":{\"type\":\"JSON\",\"value\":{\"ab10_variation\":2}}},{\"allocation\":10,\"id\":\"xxxxxx8bcahim7varnvg\",\"modifications\":{\"type\":\"JSON\",\"value\":{\"ab10_variation\":7}}},{\"allocation\":10,\"id\":\"xxxxxx8bcahim87nuosg\",\"modifications\":{\"type\":\"JSON\",\"value\":{\"ab10_variation\":3}}},{\"allocation\":10,\"id\":\"xxxxxxc3fk9jdf73j3h0\",\"modifications\":{\"type\":\"JSON\",\"value\":{\"ab10_variation\":5}}},{\"allocation\":10,\"id\":\"xxxxxxgbcahim831l72g\",\"modifications\":{\"type\":\"JSON\",\"value\":{\"ab10_variation\":9}}},{\"allocation\":10,\"id\":\"xxxxxxgbcahim8umkmf0\",\"modifications\":{\"type\":\"JSON\",\"value\":{\"ab10_variation\":6}}},{\"allocation\":10,\"id\":\"xxxxxxk3fk9jdf9curog\",\"modifications\":{\"type\":\"JSON\",\"value\":{\"ab10_variation\":8}}},{\"allocation\":10,\"id\":\"xxxxxxk3fk9jdgcbpac0\",\"modifications\":{\"type\":\"JSON\",\"value\":{\"ab10_variation\":4}}}],\"id\":\"xxxxxxc3fk9jdb020ulg\"}],\"id\":\"xxxxxxc3fk9jdb020ukg\",\"type\":\"ab\"}]}";
}
