name: Build and deploy CI for QA

on: workflow_dispatch

jobs:
  buildqa:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: go to demoqa
        run: cd ./demoqa
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: change branch
        run: sed -i 's/%branch%/${{ steps.extract_branch.outputs.branch }}/g' ./src/main/resources/static/index.html

      - name: Gradle wrapper
        run: gradle wrapper
      - name: Clean
        run: ./gradlew clean
      - name: Assemble
        run: ./gradlew assemble
      - name: test
        run: ./gradlew test

      - uses: actions/upload-artifact@v2
        with:
          name: demoqa-jar
          path: build/libs/demoqa-0.0.1.jar

  deployqa:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: demoqa-jar

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_QA }}
          
#hashtag pour les gars

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.3.0
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.extract_branch.outputs.branch }}
