
name: Generate Artifact

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      #- name: Gradle wrapper
       # run: gradle wrapper
      - name: Build
        run: |
          bash ./gradlew clean
          bash ./gradlew generateBuildConfig
          bash ./gradlew assemble
          bash ./gradlew test
          bash ./gradlew publishJarPublicationToLocalRepository
          bash ./gradlew genArtifactFolder
      - name: Get branch
        run: echo "::set-output name=branch_name::${GITHUB_REF##*/}"
        id: ref
      - name: Push artifact
        uses: actions/upload-artifact@v2
        with:
          name: java-sdk-${{ steps.ref.outputs.branch_name }}
          path: flagship/build/publications/artifact/
          retention-days: 10
