
name: Generate Artifact

on: workflow_dispatch

jobs:
 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle wrapper
        run: gradle wrapper
      - name: Build
        run: | 
           bash ./gradlew clean
           bash ./gradlew generateBuildConfig
           bash ./gradlew assemble
           bash ./gradlew test
      - name: Send greeting
        run: |
          echo "Hello ${{ github.event.inputs.name }}"
          echo ${GITHUB_REF##*/}
      - name: Push artifact
        uses: actions/upload-artifact@v2
        with:
          name: java-sdk-${GITHUB_REF}
          path: flagship/build/libs/flagship-java-1.0.0.jar
          retention-days: 10
