# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CD Release & Publish

on:
  push:
    tags:
      - '*.*.*'
      - '*.*'

jobs:
  build:
    env:
      FLAGSHIP_VERSION_NAME: FLAGSHIP_VERSION_NAME::${GITHUB_REF/refs\/tags\//}
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_KEY: ${{ secrets.ARTIFACTORY_KEY }}

    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '#ci-auto') == false
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Env
      run: |
            echo ::exportVariable name=FLAGSHIP_VERSION_NAME::${GITHUB_REF/refs\/tags\//}
            echo ::exportVariable name=ARTIFACTORY_USER::${{ secrets.ARTIFACTORY_USER }}
            echo ::exportVariable name=ARTIFACTORY_KEY::${{ secrets.ARTIFACTORY_KEY }}
    - name: Debug
      run: |
            echo $FLAGSHIP_VERSION_NAME
            echo $ARTIFACTORY_USER
            echo $ARTIFACTORY_KEY
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle wrapper
      run: gradle wrapper
    - name: Release (clean, assemble, test, publish)
      run: ./gradlew release
      
