
name: CD Release & Publish

on:
  push:
    tags:
      - '*.*.*'
# - '*.*'


jobs:
  build:
    name: Run Unit Tests
    runs-on: ubuntu-latest
   # if: contains(github.event.head_commit.message, '#ci-auto') == false
    steps:
    - uses: actions/checkout@v2.2.0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8  
    - name: Env
      run: |
        echo ::exportVariable name=FLAGSHIP_VERSION_NAME::${GITHUB_REF#refs/tags/}
        echo "::exportVariable name=FLAGSHIP_VERSION_NAME2::${GITHUB_REF#refs/tags/}"
        echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
        echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        echo "FLAGSHIP_VERSION_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        echo "${GITHUB_REF#refs/tags/}"
        echo ${GITHUB_REF#refs/tags/}
        echo $FLAGSHIP_VERSION_NAME
        echo $FLAGSHIP_VERSION_NAME2
        echo $TAG_VERSION
        echo $VERSION
    - name: Env2
      run: |
        echo $FLAGSHIP_VERSION_NAME
        echo $TAG_VERSION
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle wrapper
      run: gradle wrapper
    - name: Release (clean, assemble, test, publish)
      env:
        ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
        ARTIFACTORY_KEY: ${{ secrets.ARTIFACTORY_KEY }}
       # FLAGSHIP_VERSION_NAME: ${GITHUB_REF#refs/tags/}
      run: bash ./gradlew release
      
