
name: CD Release & Publish

#on:
#  push:
#    tags:
#      - '*.*.*'
# - '*.*'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      FLAGSHIP_VERSION_NAME: ${GITHUB_REF#refs/tags/}
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_KEY: ${{ secrets.ARTIFACTORY_KEY }}
    name: Run Unit Tests
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '#ci-auto') == false
    steps:
    - uses: actions/checkout@v2.2.0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Env
      run: |
            echo ::exportVariable name=FLAGSHIP_VERSION_NAME::${GITHUB_REF#refs/tags/}
            echo ::exportVariable name=ARTIFACTORY_USER::${{ secrets.ARTIFACTORY_USER }}
            echo ::exportVariable name=ARTIFACTORY_KEY::${{ secrets.ARTIFACTORY_KEY }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle wrapper
      run: gradle wrapper
    - name: Release (clean, assemble, test, publish)
      run: bash ./gradlew release
      
