# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Artifactory rollback CI

on:
  delete:
    tags:
      - '*.*.*'
      - '*.*'

jobs:
  proceed:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Artifactory delete version
      run: |
        curl --location --request DELETE 'https://abtasty.jfrog.io/artifactory/flagship-java/com/abtasty/flagship-java/${{ github.event.ref }}' --header 'Authorization: Bearer ${{ secrets.ARTIFACTORY_TOKEN }}'
